pre_deploy: "./predeploy.sh"
artifact_file: "./sample"
start: "nohup ./sample &>/dev/null &"
project_name: "sample-project"
domain: "syneo.io"
lb: true
SizeSlug: "s-1vcpu-1gb"
NumDroplets: 1
Region: "sfo2"
ImageSlug: "ubuntu-18-04-x64"
