#pre deploy steps
test: []
build: ["", "", ""]
project_id: "30d154e8-a45c-4f2f-8228-e768bc0d4d73"
#deploy info
domain: syneo.io
lb: true
SizeSlug: "sampleSizeSlug"
NumDroplets: 3
Region: "sampleRegionSlug"
ImageSlug: "sampleImageSlug"
key_location: ''
start: [""]
