#pre deploy steps
test: []
build: ["", "", ""]
project_id: "30d154e8-a45c-4f2f-8228-e768bc0d4d73"
#deploy info
domain: syneo.io
lb: true
SizeSlug: "s-1vcpu-1gb"
NumDroplets: 3
Region: "sfo2"
ImageSlug: "ubuntu-18-04-x64"
key_location: ''
start: [""]
