test: []
build: ["", "", ""]
project_name: "sample-project"
domain: "syneo.io"
lb: true
SizeSlug: "s-1vcpu-1gb"
NumDroplets: 0 
Region: "sfo2"
ImageSlug: "ubuntu-18-04-x64"
key_location: ''
start: [""]
